#pragma once
#include "cDialog.h"
#include "cMap.h"
#include "cObject.h"
#include "cScript.h"
#include "uiAccelator.h"
// #include "uiAddpoint.h"
#include "uiChannel.h"
// #include "uiDazao.h"
#include "uiDye.h"
// #include "uiFriend.h"
#include "uiFoot.h"
// #include "uiGrids.h"

#include "uiHeader.h"
// #include "uiInputNO.h"
#include "uiItem.h"
#include "uiJob.h"
#include "uiLearn.h"
#include "uiManager.h"
#include "uiMenu.h"
#include "uiPet.h"
// #include "uiRank.h"
#include "uiSee.h"
#include "uiShichen.h"
#include "uiShop.h"
#include "uiSkill.h"
#include "uiSkiSelect.h"
#include "uiSmap.h"
#include "uiState.h"
#include "uiWorld.h"